services:

  alpdeskcore.backendmenulistener:
    class: Alpdesk\AlpdeskCore\Events\Listener\AlpdeskCoreBackendMenuListener
    arguments:
      - '@security.helper'
      - '@router'
      - '@request_stack'
    tags:
      - { name: kernel.event_listener, event: contao.backend_menu_build, priority: -255 }

  alpdeskcore.listener.registerplugin:
    class: Alpdesk\AlpdeskCore\Events\Listener\AlpdeskCoreRegisterPluginListener
    tags:
      - { name: kernel.event_listener, event: alpdesk.registerplugin }

  alpdeskcore.listener.helloplugin:
    class: Alpdesk\AlpdeskCore\Elements\Hello\AlpdeskCoreElementHello
    tags:
      - { name: kernel.event_listener, event: alpdesk.plugincall }

  alpdeskcore.listener.contaocrud:
    class: Alpdesk\AlpdeskCore\Elements\Contao\AlpdeskCoreElementContao
    tags:
      - { name: kernel.event_listener, event: alpdesk.plugincall }
    arguments:
      - '@database_connection'
