services:

  alpdeskcore.listener.contao_generatesymlinks:
    class: Alpdesk\AlpdeskCore\Events\Listener\AlpdeskCoreEventContaoGenerateSymlinkListener
    tags:
      - { name: kernel.event_listener, event: contao.generate_symlinks}
      
  alpdeskcore.listener.registerplugin:
    class: Alpdesk\AlpdeskCore\Events\Listener\AlpdeskCoreRegisterPluginListener
    tags:
      - { name: kernel.event_listener, event: alpdesk.registerplugin}
      
  alpdeskcore.listener.helloplugin:
    class: Alpdesk\AlpdeskCore\Elements\Hello\AlpdeskCoreElementHello
    tags:
      - { name: kernel.event_listener, event: alpdesk.plugincall}    